patchesJson6902:
- path: ingress_hostname_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress-to-emp-api
    version: v1
patchesStrategicMerge:
- increase_replicas.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: juggernaut/k8s-demo-emp-api
  newName: juggernaut/k8s-demo-emp-api
  newTag: 251ace5
