patchesJson6902:
- path: ingress_hostname_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress-to-emp-api
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- digest: sha256:3c7c767ace4cb1b2ea06001862e553a2c2479047eb29881ed78e37b90cfbd70b
  name: juggernaut/k8s-demo-emp-api
  newName: juggernaut/k8s-demo-emp-api
