patchesJson6902:
- path: ingress_hostname_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress-to-emp-api
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: juggernaut/k8s-demo-emp-api
  newName: juggernaut/k8s-demo-emp-api
  newTag: fc86b3f
